\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{sduthesis}[Thesis template for undergraduates of SDU, by Zhukang Wang, zhukangwang1005@gmail.com]


% 基于ctexbook的类
\LoadClass[openany]{ctexbook}

% 导入各项配置
\input{config/main/config-main.tex}
\input{config/others/config-coverpage.tex}
\input{config/others/config-abstract.tex}
\input{config/others/config-contents.tex}
\input{config/others/config-bibliography.tex}
\input{config/others/config-acknowledgement.tex}
\input{config/others/config-appendix.tex}


\endinput
